name: release

on:
  push:
    branches:
      - live
  workflow_dispatch:

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare scenarios to be released.
      run: |
        sudo apt install zip
        zip -r scenarios.zip scenarios
    - name: Set Release Tag
      id: set_tag
      run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"

    - name: Create or Update Draft Release
      id: create_draft_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.set_tag.outputs.tag }}
        release_name: Release ${{ github.run_number }}
        body: |
          Changes in this release.

    - name: Upload scenarios.zip to Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_draft_release.outputs.upload_url }}
        asset_path: ./scenarios.zip
        asset_name: scenarios.zip
