name: release

on:
  push:
    branches:
      - live

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare scenarios to be released.
      run: |
        sudo apt install zip
        zip -r scenarios.zip scenarios
    - name: Release Executable Doc Scenarios
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: "ExecDocScenarios"
        automatic_release_tag: "latest"
        prerelease: true
        files: |
          ./scenarios.zip
